[I 17:07:53.038 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 17:07:55.108 NotebookApp] Serving notebooks from local directory: /home/xuanli2/CSE-544-Project
[I 17:07:55.109 NotebookApp] 0 active kernels
[I 17:07:55.109 NotebookApp] The Jupyter Notebook is running at:
[I 17:07:55.109 NotebookApp] http://0.0.0.0:8888/
[I 17:07:55.109 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 17:07:56.725 NotebookApp] Forbidden
[W 17:07:56.725 NotebookApp] 403 GET /api/sessions?_=1524934590573 (130.245.70.29) 1.72ms referer=http://35.196.26.71:8888/tree?
[W 17:07:56.727 NotebookApp] Forbidden
[W 17:07:56.727 NotebookApp] 403 GET /api/terminals?_=1524934590574 (130.245.70.29) 1.03ms referer=http://35.196.26.71:8888/tree?
[I 17:07:56.919 NotebookApp] 302 GET /tree? (130.245.70.29) 0.86ms
[I 17:07:59.147 NotebookApp] 302 POST /login?next=%2Ftree%3F (130.245.70.29) 1.17ms
[I 17:08:27.490 NotebookApp] 302 GET /tree (129.49.100.149) 0.89ms
[I 17:08:31.260 NotebookApp] 302 POST /login?next=%2Ftree (129.49.100.149) 1.14ms
[I 17:08:37.619 NotebookApp] Kernel started: a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 17:08:38.380 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 17:08:38.423 NotebookApp] 302 GET /tree/data (129.49.100.188) 0.96ms
[W 17:08:38.540 NotebookApp] Forbidden
[W 17:08:38.540 NotebookApp] 403 GET /api/sessions?_=1524945471339 (129.49.100.188) 1.15ms referer=http://35.196.26.71:8888/tree/data
[W 17:08:38.541 NotebookApp] Forbidden
[W 17:08:38.542 NotebookApp] 403 GET /api/terminals?_=1524945471340 (129.49.100.188) 0.74ms referer=http://35.196.26.71:8888/tree/data
[I 17:08:41.872 NotebookApp] 302 POST /login?next=%2Ftree%2Fdata (129.49.100.188) 1.22ms
[I 17:08:51.564 NotebookApp] Kernel started: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:08:52.091 NotebookApp] Adapting to protocol v5.1 for kernel 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:05.582 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:05.752 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:06.157 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:06.336 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:06.522 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:06.711 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:06.889 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:09:21.747 NotebookApp] Saving file at /Spider.ipynb
[I 17:09:24.060 NotebookApp] Saving file at /Spider.ipynb
[I 17:09:25.333 NotebookApp] Saving file at /Spider.ipynb
[I 17:09:35.071 NotebookApp] Saving file at /Spider.ipynb
[I 17:09:38.178 NotebookApp] Saving file at /Spider.ipynb
[I 17:09:59.979 NotebookApp] Saving file at /Spider.ipynb
[I 17:10:37.644 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:10:51.606 NotebookApp] Saving file at /Spider.ipynb
[I 17:12:37.684 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:12:49.369 NotebookApp] 302 GET /tree? (130.245.70.141) 0.89ms
[I 17:12:51.507 NotebookApp] 302 POST /login?next=%2Ftree%3F (130.245.70.141) 1.15ms
[W 17:14:11.538 NotebookApp] 400 GET /api/contents/data/dump/word_access_timestamps_0-5000.pkl?type=file&format=text&_=1524946483857 (129.49.100.188): /home/xuanli2/CSE-544-Project/data/dump/word_access_timestamps_0-5000.pkl is not UTF-8 encoded
[W 17:14:11.538 NotebookApp] /home/xuanli2/CSE-544-Project/data/dump/word_access_timestamps_0-5000.pkl is not UTF-8 encoded
[W 17:14:11.539 NotebookApp] 400 GET /api/contents/data/dump/word_access_timestamps_0-5000.pkl?type=file&format=text&_=1524946483857 (129.49.100.188) 2837.90ms referer=http://35.196.26.71:8888/edit/data/dump/word_access_timestamps_0-5000.pkl
[W 17:14:28.939 NotebookApp] 400 GET /api/contents/data/dump/word_access_timestamps_10000-15000.pkl?type=file&format=text&_=1524935664100 (129.49.100.149): /home/xuanli2/CSE-544-Project/data/dump/word_access_timestamps_10000-15000.pkl is not UTF-8 encoded
[W 17:14:28.939 NotebookApp] /home/xuanli2/CSE-544-Project/data/dump/word_access_timestamps_10000-15000.pkl is not UTF-8 encoded
[W 17:14:28.940 NotebookApp] 400 GET /api/contents/data/dump/word_access_timestamps_10000-15000.pkl?type=file&format=text&_=1524935664100 (129.49.100.149) 4754.89ms referer=http://35.196.26.71:8888/edit/data/dump/word_access_timestamps_10000-15000.pkl
[I 17:14:37.705 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:15:39.585 NotebookApp] Kernel started: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 17:15:40.133 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 17:16:37.643 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:17:39.663 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:18:37.689 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:19:39.632 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:20:37.660 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:21:55.579 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
[I 17:22:37.650 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:23:39.673 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:24:37.700 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:25:25.777 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:39.647 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:48.526 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:51.035 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:54.002 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:54.680 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:57.389 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:25:58.964 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:26:02.274 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:26:03.809 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:26:37.691 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:27:25.663 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:27:28.421 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:27:31.753 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:27:32.871 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:27:39.663 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:27:49.472 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:28:37.679 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:29:39.658 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:29:44.019 NotebookApp] 302 GET /login?next=%2Ftree%2Fdata (129.49.100.188) 0.71ms
[I 17:30:11.875 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 17:30:37.717 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:32:37.716 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:33:39.672 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:34:35.105 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:34:37.763 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:34:39.307 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:34:41.858 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:35:11.683 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 17:35:30.332 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:35:38.843 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:35:43.359 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:35:44.267 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:35:49.492 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:36:08.864 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:36:37.700 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:36:52.295 NotebookApp] Saving file at /Spider.ipynb
[I 17:37:00.037 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:04.013 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:07.184 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:25.495 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:26.230 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:28.764 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:35.456 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:39.663 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:37:42.108 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:38:06.908 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:38:37.705 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:39:41.654 NotebookApp] Saving file at /Spider.ipynb
[I 17:39:41.860 NotebookApp] Saving file at /Spider.ipynb
[I 17:39:45.172 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:39:45.351 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:39:45.538 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:39:45.742 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:39:45.930 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:39:46.125 NotebookApp] Kernel interrupted: 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 17:40:37.733 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:40:53.899 NotebookApp] Saving file at /Spider.ipynb
[I 17:41:08.817 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:11.637 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:15.441 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:15.817 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:19.832 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:22.709 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:24.331 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:28.852 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:30.277 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:31.885 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:40.053 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:41:48.651 NotebookApp] Kernel started: e65d15ed-a5fa-43be-8781-cef0da9d2652
[I 17:41:49.201 NotebookApp] Adapting to protocol v5.1 for kernel e65d15ed-a5fa-43be-8781-cef0da9d2652
[I 17:41:57.210 NotebookApp] Kernel started: 6de5cc05-afdd-419b-807a-244652b568d7
[I 17:41:57.800 NotebookApp] Adapting to protocol v5.1 for kernel 6de5cc05-afdd-419b-807a-244652b568d7
[I 17:42:37.700 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:44:37.774 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:45:05.032 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:05.908 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:09.910 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:20.849 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:26.681 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:32.018 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:38.496 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:39.503 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:48.475 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:49.528 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:45:50.683 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:46:37.791 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:48:37.778 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:50:11.862 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:15.684 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:24.673 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:33.016 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:33.450 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:34.342 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:50:52.330 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:11.342 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:29.433 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 17:51:30.658 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:34.077 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:39.705 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:43.530 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:47.835 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:51:48.446 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:04.998 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:05.993 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:18.659 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:19.217 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:29.996 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:40.674 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:51.374 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:52:56.122 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:03.534 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:17.425 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:23.238 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:26.527 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:33.889 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:53:39.980 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:40.035 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:44.959 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:46.850 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:53:49.651 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:54:02.335 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:54:08.928 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:54:13.865 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:54:16.330 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:55:33.905 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:55:39.711 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:56:26.919 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:56:28.669 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:56:48.559 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:03.412 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:05.168 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:05.715 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:26.907 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:27.565 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:57:33.883 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:57:38.907 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:05.297 NotebookApp] Starting buffering for 6de5cc05-afdd-419b-807a-244652b568d7:a9575cb154a84af68c1d8e690f3396e4
[I 17:58:05.813 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:06.852 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:11.426 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:12.203 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:14.839 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:46.543 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:58:52.338 NotebookApp] Saving file at /Spider.ipynb
[I 17:59:17.340 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:18.943 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:29.466 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:31.138 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:33.887 NotebookApp] Saving file at /DataEvents.ipynb
[I 17:59:39.728 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:40.077 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 17:59:40.707 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:00:40.272 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:02.115 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:02.660 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:10.183 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:19.720 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:22.637 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:27.549 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:38.644 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:01:39.732 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:50.420 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:55.169 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:56.253 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:01:57.519 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:03:39.742 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:04:37.100 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:04:38.673 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:04:42.766 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:04:59.074 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:05:17.474 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:05:18.081 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:05:26.169 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:05:39.743 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:09:32.616 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:10:49.097 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:11:00.752 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:11:07.037 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:14:43.286 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:21:23.602 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:21:33.165 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:21:34.584 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:21:38.517 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:21:53.665 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:21:54.248 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:21:56.583 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:04.086 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:07.550 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:08.721 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:09.484 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:10.720 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:22:43.367 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:22:52.399 NotebookApp] Saving file at /Spider.ipynb
[I 18:25:07.290 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:25:40.430 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:24.351 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:27.281 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:28.072 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:31.932 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:35.819 NotebookApp] Saving file at /Revision Analysis.ipynb
[W 18:26:38.381 NotebookApp] WebSocket ping timeout after 119895 ms.
[I 18:26:50.856 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:54.397 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:55.367 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:26:59.537 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:01.972 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:13.329 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:14.461 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:16.193 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:18.272 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:19.664 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:25.102 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:27:39.796 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:28:27.221 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:29:16.607 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:29:33.182 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 18:29:39.808 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:18.913 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:22.068 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:22.603 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:31:34.136 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:36.532 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:41.415 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:31:43.367 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:32:55.457 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:32:56.216 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:09.290 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:37.383 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:38.821 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:39.809 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:40.259 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:43.953 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:33:44.631 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:34:13.358 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:34:15.869 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:34:21.009 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:34:36.750 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:34:38.948 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:03.199 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:05.134 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 18:35:05.909 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:07.014 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:28.173 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:28.732 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:37.123 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:37.830 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:38.413 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:40.729 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:45.090 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:46.202 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:50.402 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:53.286 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:35:59.548 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:01.167 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:12.571 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:13.278 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:15.687 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:20.361 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:21.571 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:23.049 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:25.141 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:25.950 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:28.396 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:36.504 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:39.254 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:45.805 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:46.322 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:47.218 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:48.735 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:57.312 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:36:59.162 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:00.217 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:06.043 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:37:18.741 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:24.111 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:24.938 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:28.881 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:38.324 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:39.814 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:40.727 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:41.471 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:45.035 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:51.481 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:53.911 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:55.037 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:37:59.220 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:00.761 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:05.970 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:08.701 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:09.127 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:38:10.156 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:13.700 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:18.588 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:25.174 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:28.495 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:29.202 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:34.210 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:34.979 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:36.361 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:38.300 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:47.129 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:54.545 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:55.226 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:38:56.073 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:13.346 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:19.207 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:25.250 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:25.900 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:39.820 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:39.984 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:40.615 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:41.197 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:42.502 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:44.688 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:46.796 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:39:48.966 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.135 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.305 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.478 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.640 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.811 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:49.976 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:50.137 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:39:50.299 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:40:05.308 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:40:08.090 NotebookApp] Starting buffering for 33a182f8-5f19-47e9-ae39-605da6fefbab:754fbd63d54f40a98438e69738c1414c
[I 18:40:09.031 NotebookApp] Adapting to protocol v5.1 for kernel 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 18:40:57.677 NotebookApp] Saving file at /Spider.ipynb
[I 18:40:57.968 NotebookApp] Starting buffering for 33a182f8-5f19-47e9-ae39-605da6fefbab:43790929f902409289f36f21e1984aa5
[I 18:41:02.609 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:02.788 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:02.966 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:03.112 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:05.715 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:8ed9d5f0ae1845d18a09e76fa4d8c57b
[I 18:41:10.826 NotebookApp] Kernel restarted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:11.492 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 18:41:11.493 NotebookApp] Restoring connection for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:8ed9d5f0ae1845d18a09e76fa4d8c57b
[I 18:41:23.757 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:41:28.885 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:41:43.174 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:42:05.317 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:43:43.154 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:44:05.343 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:44:38.169 NotebookApp] Saving file at /Revision Analysis.ipynb
[W 18:44:53.184 NotebookApp] 400 GET /api/contents/data/revisions/revision_records.pkl?type=file&format=text&_=1524951925675 (129.49.100.188): /home/xuanli2/CSE-544-Project/data/revisions/revision_records.pkl is not UTF-8 encoded
[W 18:44:53.185 NotebookApp] /home/xuanli2/CSE-544-Project/data/revisions/revision_records.pkl is not UTF-8 encoded
[W 18:44:53.185 NotebookApp] 400 GET /api/contents/data/revisions/revision_records.pkl?type=file&format=text&_=1524951925675 (129.49.100.188) 2639.82ms referer=http://35.196.26.71:8888/edit/data/revisions/revision_records.pkl
[I 18:45:43.151 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:05.294 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:46:16.109 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:16.923 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:32.445 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:42.468 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:49.371 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:51.115 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:46:52.883 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:47:43.165 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:47:56.716 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:05.311 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:48:05.854 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:07.822 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:20.212 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:22.345 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:23.782 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:27.887 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:28.736 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:45.033 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:51.160 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:53.890 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:48:59.460 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:12.571 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:13.338 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:16.294 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:24.306 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:25.099 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:27.176 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:49:43.165 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:50:05.327 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:50:18.774 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:50:19.409 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:50:37.291 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:50:39.455 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:51:43.169 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:05.410 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:52:15.978 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:16.650 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:17.707 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:25.108 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:25.543 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:26.091 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:28.410 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:30.777 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:44.628 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:52:48.425 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:03.475 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:04.870 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:07.804 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:11.452 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:13.317 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:28.887 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:30.408 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:36.002 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:38.347 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:39.942 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:43.169 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:44.242 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:45.272 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:46.828 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:47.926 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:50.205 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:53.346 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:55.711 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:53:58.737 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:54:01.025 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:54:03.234 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:54:04.123 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:54:05.342 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:54:07.065 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:54:13.543 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:56:02.476 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:56:03.029 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:56:05.336 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:56:07.868 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:56:10.769 NotebookApp] Starting buffering for e65d15ed-a5fa-43be-8781-cef0da9d2652:940e7b58ce7d4666866e903369633c87
[I 18:57:03.010 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:57:03.512 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:03.825 NotebookApp] Adapting to protocol v5.1 for kernel 33a182f8-5f19-47e9-ae39-605da6fefbab
[I 18:58:05.346 NotebookApp] Saving file at /DataEvents.ipynb
[I 18:58:19.295 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:44.671 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:47.650 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:50.127 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:51.786 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:56.643 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:58:59.746 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:03.302 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:18.285 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:22.993 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:24.184 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:43.426 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:49.100 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:50.577 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:57.354 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 18:59:59.605 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:01.482 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:02.523 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:04.470 NotebookApp] Saving file at /Spider.ipynb
[I 19:00:05.318 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:00:14.743 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:20.540 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:24.260 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:28.618 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:32.304 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:34.104 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:39.574 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:47.730 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:52.632 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:00:56.786 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:00.099 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:03.306 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:16.684 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:18.352 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:22.864 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:42.157 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:43.191 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:47.452 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:48.589 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:01:51.552 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:06.919 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:02:08.562 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:11.417 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:16.513 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:21.576 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:23.525 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:24.879 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:33.055 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:35.997 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:41.367 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:46.629 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:47.926 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:54.983 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:56.756 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:02:57.986 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:01.174 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:06.082 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:13.851 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:15.165 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:17.434 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:19.309 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:19.903 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:24.011 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:24.570 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:33.756 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:36.089 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:37.354 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:37.804 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:41.740 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:51.832 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:55.800 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:58.398 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:03:59.122 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:04:00.630 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:04:02.816 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:04:06.921 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:04:26.237 NotebookApp] Saving file at /Spider.ipynb
[I 19:05:37.570 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:41.933 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:43.949 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:48.807 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:49.888 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:55.237 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:55.945 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:05:57.358 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:06:04.887 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:06:06.964 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:06:33.404 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:33.907 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:34.644 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:40.463 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:8ed9d5f0ae1845d18a09e76fa4d8c57b
[I 19:06:40.988 NotebookApp] Kernel restarted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:44.774 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:44.775 NotebookApp] Restoring connection for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:8ed9d5f0ae1845d18a09e76fa4d8c57b
[I 19:06:44.775 NotebookApp] Replaying 6 buffered messages
[I 19:06:55.297 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:55.743 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:55.914 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:56.101 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:56.288 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:56.521 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:56.738 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:56.921 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:57.092 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:57.239 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:06:59.828 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:07:00.604 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:07:33.573 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:33.755 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:33.928 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.102 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.281 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.460 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.623 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.801 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:34.972 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:07:43.211 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:08:07.011 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:09:43.215 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:10:06.958 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:11:39.238 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:12:06.990 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:12:08.560 NotebookApp] New terminal with automatic name: 1
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 2: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 32: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 24: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 6: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 3: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 7: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 6: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 1: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 3: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 17: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 11: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 3: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 1: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 15: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 10: invalid start byte
[I 19:13:24.947 NotebookApp] Kernel started: 010e8f1b-a86f-41ba-9c39-3142067f6671
[I 19:13:25.510 NotebookApp] Adapting to protocol v5.1 for kernel 010e8f1b-a86f-41ba-9c39-3142067f6671
[I 19:14:06.969 NotebookApp] Saving file at /DataEvents.ipynb
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 411: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 15: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1217: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 37: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 11: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 10: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 24: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 35: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 20: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 4: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 13: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 27: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 33: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 5: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 25: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 31: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 11: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 14: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 23: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 31: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 37: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 20: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 10: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 3: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 49: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 8: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 15: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 2: invalid continuation byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 20: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 3: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(68, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(68, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/terminado/management.py", line 196, in pty_read
    s = ptywclients.ptyproc.read(65536)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 812, in read
    return self.decoder.decode(b, final=False)
  File "/home/xuanli2/penv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 17: invalid start byte
[I 19:15:25.145 NotebookApp] Saving file at /Page_Length.ipynb
[I 19:16:16.693 NotebookApp] Creating new notebook in 
[I 19:16:17.714 NotebookApp] Kernel started: 2f851684-11b6-497a-807c-648dd32ffd5a
[I 19:16:18.408 NotebookApp] Adapting to protocol v5.1 for kernel 2f851684-11b6-497a-807c-648dd32ffd5a
[I 19:18:18.133 NotebookApp] Saving file at /Untitled.ipynb
[I 19:27:41.900 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 19:28:49.983 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:29:43.661 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:30:49.946 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:32:49.950 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:34:50.131 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:36:50.024 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:37:25.380 NotebookApp] Saving file at /Page_Length.ipynb
[I 19:37:28.604 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
[I 19:38:50.014 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:39:25.229 NotebookApp] Saving file at /Page_Length.ipynb
[I 19:46:47.282 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:46:47.454 NotebookApp] Kernel interrupted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:46:47.595 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
[I 19:46:47.675 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:47.879 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:47.946 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.012 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.125 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:46:48.306 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.372 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.453 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.519 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:46:48.610 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:46:48.762 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:46:48.808 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:46:48.847 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:46:49.091 NotebookApp] Starting buffering for 33a182f8-5f19-47e9-ae39-605da6fefbab:6404b3f9ed2f47378f6fd3e94d761741
[I 19:46:49.099 NotebookApp] Starting buffering for 2f851684-11b6-497a-807c-648dd32ffd5a:f371ff10572740db8017ce1319e21fc6
[I 19:46:49.102 NotebookApp] Starting buffering for 010e8f1b-a86f-41ba-9c39-3142067f6671:9a6a4038a9a54b6caaa3435487e99463
[I 19:46:49.921 NotebookApp] Adapting to protocol v5.1 for kernel 010e8f1b-a86f-41ba-9c39-3142067f6671
[I 19:46:49.922 NotebookApp] Discarding 2 buffered messages for 010e8f1b-a86f-41ba-9c39-3142067f6671:9a6a4038a9a54b6caaa3435487e99463
[I 19:46:50.119 NotebookApp] Adapting to protocol v5.1 for kernel 2f851684-11b6-497a-807c-648dd32ffd5a
[I 19:46:51.244 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 19:47:01.858 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:47:26.768 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:8ed9d5f0ae1845d18a09e76fa4d8c57b
[I 19:47:27.987 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 19:47:33.580 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:47:34.274 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:47:53.173 NotebookApp] Starting buffering for 2f851684-11b6-497a-807c-648dd32ffd5a:396f4e3f1570426cb664b6cb4cd6deb8
[I 19:47:54.113 NotebookApp] Adapting to protocol v5.1 for kernel 2f851684-11b6-497a-807c-648dd32ffd5a
[I 19:47:56.653 NotebookApp] Starting buffering for 010e8f1b-a86f-41ba-9c39-3142067f6671:afcde86f77a341d08c09363585422810
[I 19:47:57.840 NotebookApp] Adapting to protocol v5.1 for kernel 010e8f1b-a86f-41ba-9c39-3142067f6671
[I 19:48:55.299 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:49:27.900 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:50:16.285 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
[I 19:50:16.876 NotebookApp] Saving file at /Page_Length.ipynb
[I 19:50:51.086 NotebookApp] Saving file at /DataEvents.ipynb
[W 19:51:33.184 NotebookApp] WebSocket ping timeout after 119928 ms.
[I 19:52:19.564 NotebookApp] Starting buffering for a4d8ec08-4dcb-44f7-8b88-89c400e20657:bb0ae3baa51e4166868727e6aa1b9c92
[I 19:52:22.442 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 19:52:38.291 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 19:53:27.128 NotebookApp] Saving file at /Page_Length.ipynb
[I 19:54:22.383 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:54:49.471 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:54:49.842 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 19:55:27.978 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:55:28.118 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:55:32.545 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:56:07.913 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:56:49.716 NotebookApp] Saving file at /DataEvents.ipynb
[I 19:57:28.621 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 19:58:49.741 NotebookApp] Saving file at /DataEvents.ipynb
[W 19:58:54.185 NotebookApp] IOPub data rate exceeded.
    The notebook server will temporarily stop sending output
    to the client in order to avoid crashing it.
    To change this limit, set the config variable
    `--NotebookApp.iopub_data_rate_limit`.
    
    Current values:
    NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
    NotebookApp.rate_limit_window=3.0 (secs)
    
[W 19:58:54.559 NotebookApp] IOPub data rate exceeded.
    The notebook server will temporarily stop sending output
    to the client in order to avoid crashing it.
    To change this limit, set the config variable
    `--NotebookApp.iopub_data_rate_limit`.
    
    Current values:
    NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
    NotebookApp.rate_limit_window=3.0 (secs)
    
[I 20:00:49.734 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:00:55.651 NotebookApp] Kernel interrupted: a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:02:07.556 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
WARNING:root:kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657 restarted
[I 20:02:49.767 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:04:49.765 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:06:49.722 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:08:49.752 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:10:49.958 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:12:49.824 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:14:49.781 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:16:49.782 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:17:20.624 NotebookApp] Kernel interrupted: a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:18:47.449 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:18:49.837 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:21:57.348 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:22:49.813 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:23:54.538 NotebookApp] Kernel interrupted: a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:24:49.820 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:25:17.022 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:26:49.842 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:28:39.733 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:28:49.848 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:28:51.319 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:30:50.106 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:31:27.653 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:31:46.087 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:32:49.871 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:34:37.212 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:34:49.933 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:36:35.767 NotebookApp] Saving file at /DataEvents.ipynb
[I 20:37:47.205 NotebookApp] Saving file at /Page_Length.ipynb
[W 20:40:49.844 NotebookApp] WebSocket ping timeout after 119891 ms.
[I 20:42:49.793 NotebookApp] Starting buffering for 2f851684-11b6-497a-807c-648dd32ffd5a:c05b112b76264f1ca56cde0e558350f3
[I 20:42:49.794 NotebookApp] Starting buffering for 010e8f1b-a86f-41ba-9c39-3142067f6671:7e556ba60b7f4db5a15202f3a8d91894
[W 20:42:51.320 NotebookApp] WebSocket ping timeout after 119973 ms.
[I 20:42:56.322 NotebookApp] Starting buffering for a4d8ec08-4dcb-44f7-8b88-89c400e20657:f06074dad5af44828dd75a0f2f2548ba
[I 20:44:11.667 NotebookApp] 302 GET / (130.245.70.141) 0.48ms
[I 20:44:18.592 NotebookApp] Adapting to protocol v5.1 for kernel 010e8f1b-a86f-41ba-9c39-3142067f6671
[I 20:44:46.427 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:09e90362eb9048a081c089fcba99c194
[I 20:44:47.846 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 20:45:31.956 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:45:36.628 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:46:18.685 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:47:38.422 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:c6b0572ff3cb4eda890a1b32b7e72d6a
[I 20:47:43.375 NotebookApp] Kernel restarted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 20:47:46.922 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 20:47:46.923 NotebookApp] Restoring connection for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:c6b0572ff3cb4eda890a1b32b7e72d6a
[I 20:47:46.923 NotebookApp] Replaying 6 buffered messages
[I 20:47:50.242 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:48:04.123 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:48:05.171 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:48:18.529 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:48:32.845 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:48:47.791 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:48:52.722 NotebookApp] 302 GET /tree? (130.245.192.0) 0.93ms
[I 20:48:59.682 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:48:59.967 NotebookApp] 302 POST /login?next=%2Ftree%3F (130.245.192.0) 1.20ms
[I 20:49:06.434 NotebookApp] Adapting to protocol v5.1 for kernel 6de5cc05-afdd-419b-807a-244652b568d7
[I 20:49:13.342 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:14.987 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:16.335 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:17.349 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:17.875 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:28.712 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:29.648 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:32.327 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:45.518 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:49.495 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:51.527 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:49:54.624 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:08.488 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:09.224 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:11.708 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:18.754 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:19.402 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:50:27.358 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:29.227 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:39.525 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:43.111 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:50:47.786 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:51:06.456 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[W 20:51:48.771 NotebookApp] Forbidden
[W 20:51:48.772 NotebookApp] 403 GET /api/sessions?_=1524858330471 (148.75.183.246) 1.34ms referer=http://35.196.26.71:8888/tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[W 20:51:48.779 NotebookApp] Forbidden
[W 20:51:48.779 NotebookApp] 403 GET /api/terminals?_=1524858330472 (148.75.183.246) 0.95ms referer=http://35.196.26.71:8888/tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[W 20:51:50.834 NotebookApp] Forbidden
[W 20:51:50.834 NotebookApp] 403 GET /api/contents/data?type=directory&_=1524858330473 (148.75.183.246) 1.17ms referer=http://35.196.26.71:8888/tree/data
[W 20:51:53.168 NotebookApp] Forbidden
[W 20:51:53.169 NotebookApp] 403 GET /api/contents?type=directory&_=1524858330474 (148.75.183.246) 1.12ms referer=http://35.196.26.71:8888/tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[I 20:51:55.908 NotebookApp] 302 GET /tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 0.96ms
[W 20:52:06.626 NotebookApp] 401 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 4.69ms referer=http://35.196.26.71:8888/login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[I 20:52:17.627 NotebookApp] 302 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 4.69ms
[I 20:52:18.564 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:52:46.738 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 20:53:12.142 NotebookApp] Starting buffering for a4d8ec08-4dcb-44f7-8b88-89c400e20657:bf5ff78cdda443258b4c0082d05d71e9
[I 20:53:26.041 NotebookApp] Kernel started: 71ab1378-d1aa-46dd-836c-5532e4ed4da7
[I 20:53:26.575 NotebookApp] Adapting to protocol v5.1 for kernel 71ab1378-d1aa-46dd-836c-5532e4ed4da7
[I 20:53:38.434 NotebookApp] Kernel started: cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e
[I 20:53:38.965 NotebookApp] Adapting to protocol v5.1 for kernel cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e
[I 20:53:56.735 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:54:19.410 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:55:06.106 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:07.590 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:09.973 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:23.074 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:23.917 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:26.499 NotebookApp] Saving file at /Playground_Xiaofei.ipynb
[I 20:55:34.300 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:34.988 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:37.604 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:38.480 NotebookApp] Saving file at /Untitled1.ipynb
[I 20:55:39.247 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:44.422 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:55:45.713 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:01.442 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:18.556 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:56:31.912 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:35.215 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:37.252 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:42.510 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:56:46.036 NotebookApp] Starting buffering for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:c6b0572ff3cb4eda890a1b32b7e72d6a
[I 20:56:46.546 NotebookApp] Kernel restarted: 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 20:56:47.290 NotebookApp] Adapting to protocol v5.1 for kernel 4f9a898f-d77f-45e1-a1de-9963c47f2baa
[I 20:56:47.291 NotebookApp] Restoring connection for 4f9a898f-d77f-45e1-a1de-9963c47f2baa:c6b0572ff3cb4eda890a1b32b7e72d6a
[I 20:56:47.291 NotebookApp] Replaying 5 buffered messages
[I 20:56:57.220 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:57:01.404 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:22.543 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:27.753 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:31.482 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:33.183 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:37.217 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:49.456 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:54.206 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:55.698 NotebookApp] New terminal with automatic name: 2
[I 20:57:58.652 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:59.257 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:57:59.943 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:00.982 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:05.052 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:13.477 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:14.135 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:19.627 NotebookApp] Saving file at /Page_Length.ipynb
[I 20:58:19.950 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:20.655 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:21.254 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:50.611 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:52.791 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:53.296 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:53.975 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:58:55.715 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:11.218 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:20.817 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:21.282 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:21.747 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:22.466 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 20:59:40.420 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:00:18.731 NotebookApp] Saving file at /Page_Length.ipynb
[I 21:00:47.846 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:02:13.013 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:02:13.259 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:02:13.582 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:02:30.186 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:02:47.822 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:03:16.483 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:03:39.280 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:03:57.767 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:05.567 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:11.873 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:20.763 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:21.512 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:22.184 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:34.858 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:35.592 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:47.819 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:04:51.965 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:05:05.160 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:05:07.670 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:05:36.027 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:06:47.857 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:07:59.929 NotebookApp] Adapting to protocol v5.1 for kernel 2f851684-11b6-497a-807c-648dd32ffd5a
[I 21:08:34.031 NotebookApp] Adapting to protocol v5.1 for kernel cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e
[I 21:08:36.510 NotebookApp] Starting buffering for 2f851684-11b6-497a-807c-648dd32ffd5a:7af0f5132d2b4e9c8aef10e17d9cfa32
[I 21:10:33.986 NotebookApp] Saving file at /Category.ipynb
[I 21:11:22.567 NotebookApp] Kernel interrupted: cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e
[I 21:12:34.412 NotebookApp] Saving file at /Category.ipynb
[I 21:12:47.960 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:12:55.864 NotebookApp] Creating new file in 
[I 21:13:00.181 NotebookApp] Saving file at /untitled.txt
[I 21:14:34.407 NotebookApp] Saving file at /Category.ipynb
[I 21:16:34.444 NotebookApp] Saving file at /Category.ipynb
[I 21:18:47.969 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:18:56.405 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:18:57.094 NotebookApp] Saving file at /Revision Analysis.ipynb
[W 21:28:06.865 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142897 (148.75.183.246): No such file or directory: Untitled1.ipynb
[W 21:28:06.914 NotebookApp] No such file or directory: Untitled1.ipynb
[W 21:28:06.915 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142897 (148.75.183.246) 11545.90ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[W 21:28:06.925 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142898 (148.75.183.246): No such file or directory: Untitled1.ipynb
[W 21:28:06.925 NotebookApp] No such file or directory: Untitled1.ipynb
[W 21:28:06.926 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142898 (148.75.183.246) 1.03ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[W 21:28:06.932 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142899 (148.75.183.246): No such file or directory: Untitled1.ipynb
[W 21:28:06.932 NotebookApp] No such file or directory: Untitled1.ipynb
[W 21:28:06.932 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142899 (148.75.183.246) 0.85ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[W 21:28:07.395 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142900 (148.75.183.246): No such file or directory: Untitled1.ipynb
[W 21:28:07.396 NotebookApp] No such file or directory: Untitled1.ipynb
[W 21:28:07.396 NotebookApp] 404 GET /api/contents/Untitled1.ipynb?content=0&_=1524949142900 (148.75.183.246) 0.97ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[I 21:28:07.397 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 010e8f1b-a86f-41ba-9c39-3142067f6671 restarted
[I 21:28:07.483 NotebookApp] Uploading file to /Untitled1.ipynb
[I 21:28:07.678 NotebookApp] Saving file at /Untitled1.ipynb
[I 21:28:07.698 NotebookApp] Saving file at /Untitled1.ipynb
[I 21:28:07.714 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 21:28:07.893 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 21:28:08.064 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 21:28:08.201 NotebookApp] Saving file at /Untitled1.ipynb
[I 21:28:08.458 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.535 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.567 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.618 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.658 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.691 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.727 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.763 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.813 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.846 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.896 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.956 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:08.990 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.027 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.072 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.104 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.137 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.174 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.206 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.239 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.272 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.307 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.341 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.373 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.416 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.450 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.534 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:09.568 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 21:28:25.710 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[I 21:28:51.734 NotebookApp] Saving file at /math_concept_timeline.txt
[I 21:29:07.945 NotebookApp] Saving file at /math_concept_timeline.txt
[I 21:30:17.581 NotebookApp] Starting buffering for 6de5cc05-afdd-419b-807a-244652b568d7:9b36b7a1644f4f1880ca0bd14eeb4b4b
[I 21:30:21.448 NotebookApp] Kernel restarted: 6de5cc05-afdd-419b-807a-244652b568d7
[I 21:30:22.759 NotebookApp] Adapting to protocol v5.1 for kernel 6de5cc05-afdd-419b-807a-244652b568d7
[I 21:30:22.760 NotebookApp] Restoring connection for 6de5cc05-afdd-419b-807a-244652b568d7:9b36b7a1644f4f1880ca0bd14eeb4b4b
[I 21:30:22.760 NotebookApp] Replaying 6 buffered messages
[I 21:30:48.244 NotebookApp] Adapting to protocol v5.1 for kernel 2f851684-11b6-497a-807c-648dd32ffd5a
[I 21:30:51.259 NotebookApp] Starting buffering for 2f851684-11b6-497a-807c-648dd32ffd5a:29a552dbffa0451a8600f9e73d317b2c
[I 21:31:00.525 NotebookApp] Kernel shutdown: 71ab1378-d1aa-46dd-836c-5532e4ed4da7
[I 21:31:14.586 NotebookApp] Kernel interrupted: cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e
[I 21:55:08.653 NotebookApp] Saving file at /Untitled1.ipynb
[I 21:55:47.098 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 21:56:28.975 NotebookApp] Saving file at /DataEvents.ipynb
[W 21:56:31.624 NotebookApp] Replacing stale connection: a4d8ec08-4dcb-44f7-8b88-89c400e20657:a9988dd7420d445184b20a68e0093744
[I 21:56:33.152 NotebookApp] Starting buffering for a4d8ec08-4dcb-44f7-8b88-89c400e20657:a9988dd7420d445184b20a68e0093744
[I 21:56:33.153 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 21:56:33.153 NotebookApp] Restoring connection for a4d8ec08-4dcb-44f7-8b88-89c400e20657:a9988dd7420d445184b20a68e0093744
[I 21:56:47.501 NotebookApp] Starting buffering for a4d8ec08-4dcb-44f7-8b88-89c400e20657:a9988dd7420d445184b20a68e0093744
[I 21:56:51.503 NotebookApp] Adapting to protocol v5.1 for kernel a4d8ec08-4dcb-44f7-8b88-89c400e20657
[I 22:17:32.137 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 22:17:34.096 NotebookApp] Serving notebooks from local directory: /home/xuanli2/CSE-544-Project
[I 22:17:34.096 NotebookApp] 0 active kernels
[I 22:17:34.096 NotebookApp] The Jupyter Notebook is running at:
[I 22:17:34.096 NotebookApp] http://0.0.0.0:8888/
[I 22:17:34.096 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 22:17:38.914 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:39.050 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 138.21ms referer=None
[W 22:17:41.909 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:41.911 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 2.97ms referer=None
[W 22:17:46.552 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:46.554 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 2.87ms referer=None
[W 22:17:46.912 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:46.914 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 3.21ms referer=None
[W 22:17:49.583 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:49.585 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 3.10ms referer=None
[W 22:17:53.582 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:53.583 NotebookApp] 403 GET /api/kernels/cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e/channels?session_id=e080586e7bfe4554a025f792661838f3 (130.245.70.141) 3.11ms referer=None
[W 22:17:54.598 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:54.600 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 3.45ms referer=None
[W 22:17:55.903 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:17:55.904 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 3.29ms referer=None
[W 22:18:03.551 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:03.552 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 2.77ms referer=None
[W 22:18:08.910 NotebookApp] Forbidden
[W 22:18:08.911 NotebookApp] 403 GET /api/terminals?_=1524950888548 (130.245.70.29) 1.35ms referer=http://35.196.26.71:8888/tree
[W 22:18:08.912 NotebookApp] Forbidden
[W 22:18:08.912 NotebookApp] 403 GET /api/sessions?_=1524950888547 (130.245.70.29) 0.84ms referer=http://35.196.26.71:8888/tree
[W 22:18:12.912 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:12.913 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 2.80ms referer=None
[W 22:18:20.582 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:20.583 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 3.30ms referer=None
[I 22:18:24.760 NotebookApp] 302 GET /notebooks/DataEvents.ipynb (129.49.100.188) 1.00ms
[W 22:18:32.601 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:32.602 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.95ms referer=None
[W 22:18:35.604 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:35.606 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.92ms referer=None
[W 22:18:39.668 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:39.670 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 3.37ms referer=None
[W 22:18:45.913 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:45.914 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 2.80ms referer=None
[W 22:18:47.735 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:47.737 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.90ms referer=None
[W 22:18:53.556 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:53.558 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 2.81ms referer=None
[W 22:18:58.583 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:18:58.584 NotebookApp] 403 GET /api/kernels/cf402a91-a1b5-44a4-9bf7-0fd73d09fe1e/channels?session_id=e080586e7bfe4554a025f792661838f3 (130.245.70.141) 3.49ms referer=None
[W 22:19:03.796 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:19:03.797 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.93ms referer=None
[W 22:19:08.889 NotebookApp] Forbidden
[W 22:19:08.890 NotebookApp] 403 GET /api/sessions?_=1524950888549 (130.245.70.29) 1.20ms referer=http://35.196.26.71:8888/tree
[W 22:19:08.891 NotebookApp] Forbidden
[W 22:19:08.892 NotebookApp] 403 GET /api/terminals?_=1524950888550 (130.245.70.29) 0.89ms referer=http://35.196.26.71:8888/tree
[W 22:19:35.465 NotebookApp] Forbidden
[W 22:19:35.466 NotebookApp] 403 POST /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/interrupt (130.245.192.0) 1.27ms referer=http://35.196.26.71:8888/notebooks/HongyiDuanmu.ipynb
[W 22:19:35.856 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:19:35.858 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.80ms referer=None
[W 22:19:39.148 NotebookApp] Forbidden
[W 22:19:39.149 NotebookApp] 403 POST /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/interrupt (130.245.192.0) 1.29ms referer=http://35.196.26.71:8888/notebooks/HongyiDuanmu.ipynb
[W 22:19:40.016 NotebookApp] Forbidden
[W 22:19:40.017 NotebookApp] 403 GET /api/contents/HongyiDuanmu.ipynb?content=0&_=1524948542674 (130.245.192.0) 1.27ms referer=http://35.196.26.71:8888/notebooks/HongyiDuanmu.ipynb
[W 22:19:40.126 NotebookApp] Forbidden
[W 22:19:40.126 NotebookApp] 403 PUT /api/contents/HongyiDuanmu.ipynb (130.245.192.0) 69.01ms referer=http://35.196.26.71:8888/notebooks/HongyiDuanmu.ipynb
[W 22:19:51.680 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:19:51.681 NotebookApp] 403 GET /api/kernels/4f9a898f-d77f-45e1-a1de-9963c47f2baa/channels?session_id=c6b0572ff3cb4eda890a1b32b7e72d6a (130.245.70.29) 2.81ms referer=None
[W 22:19:58.593 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:19:58.594 NotebookApp] 403 GET /api/kernels/010e8f1b-a86f-41ba-9c39-3142067f6671/channels?session_id=12f24f0c7e8547d686cbe1c80f8e0b17 (130.245.70.141) 2.96ms referer=None
[W 22:20:08.891 NotebookApp] Forbidden
[W 22:20:08.891 NotebookApp] 403 GET /api/sessions?_=1524950888551 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:20:08.892 NotebookApp] Forbidden
[W 22:20:08.893 NotebookApp] 403 GET /api/terminals?_=1524950888552 (130.245.70.29) 0.78ms referer=http://35.196.26.71:8888/tree
[I 22:20:13.308 NotebookApp] The port 8888 is already in use, trying another port.
[I 22:20:13.315 NotebookApp] Serving notebooks from local directory: /home/xuanli2/CSE-544-Project
[I 22:20:13.315 NotebookApp] 0 active kernels
[I 22:20:13.315 NotebookApp] The Jupyter Notebook is running at:
[I 22:20:13.315 NotebookApp] http://0.0.0.0:8889/
[I 22:20:13.315 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 22:20:28.448 NotebookApp] 302 GET / (130.245.70.72) 0.49ms
[I 22:20:28.606 NotebookApp] 302 GET /tree? (130.245.70.72) 0.81ms
[W 22:20:39.919 NotebookApp] Couldn't authenticate WebSocket connection
[W 22:20:39.920 NotebookApp] 403 GET /api/kernels/6de5cc05-afdd-419b-807a-244652b568d7/channels?session_id=9b36b7a1644f4f1880ca0bd14eeb4b4b (130.245.192.0) 2.73ms referer=None
[W 22:21:08.894 NotebookApp] Forbidden
[W 22:21:08.894 NotebookApp] 403 GET /api/sessions?_=1524950888553 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:21:08.895 NotebookApp] Forbidden
[W 22:21:08.895 NotebookApp] 403 GET /api/terminals?_=1524950888554 (130.245.70.29) 0.67ms referer=http://35.196.26.71:8888/tree
[C 22:21:09.586 NotebookApp] received signal 15, stopping
[I 22:21:09.587 NotebookApp] Shutting down 0 kernels
[I 22:21:29.781 NotebookApp] 302 POST /login?next=%2Ftree%3F (130.245.70.72) 1.25ms
[W 22:22:08.888 NotebookApp] Forbidden
[W 22:22:08.888 NotebookApp] 403 GET /api/sessions?_=1524950888555 (130.245.70.29) 1.19ms referer=http://35.196.26.71:8888/tree
[W 22:22:08.889 NotebookApp] Forbidden
[W 22:22:08.889 NotebookApp] 403 GET /api/terminals?_=1524950888556 (130.245.70.29) 0.68ms referer=http://35.196.26.71:8888/tree
[W 22:23:08.895 NotebookApp] Forbidden
[W 22:23:08.895 NotebookApp] 403 GET /api/terminals?_=1524950888558 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:23:08.897 NotebookApp] Forbidden
[W 22:23:08.897 NotebookApp] 403 GET /api/sessions?_=1524950888557 (130.245.70.29) 0.77ms referer=http://35.196.26.71:8888/tree
[W 22:24:08.899 NotebookApp] Forbidden
[W 22:24:08.900 NotebookApp] 403 GET /api/sessions?_=1524950888559 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:24:08.900 NotebookApp] Forbidden
[W 22:24:08.901 NotebookApp] 403 GET /api/terminals?_=1524950888560 (130.245.70.29) 0.72ms referer=http://35.196.26.71:8888/tree
[W 22:24:22.156 NotebookApp] Forbidden
[W 22:24:22.157 NotebookApp] 403 GET /api/sessions?_=1524950888926 (130.245.192.0) 1.06ms referer=http://35.196.26.71:8888/tree/data
[W 22:24:22.158 NotebookApp] Forbidden
[W 22:24:22.158 NotebookApp] 403 GET /api/terminals?_=1524950888927 (130.245.192.0) 0.65ms referer=http://35.196.26.71:8888/tree/data
[I 22:24:24.232 NotebookApp] 302 GET /tree/data (130.245.192.0) 0.90ms
[I 22:24:29.833 NotebookApp] 302 POST /login?next=%2Ftree%2Fdata (130.245.192.0) 1.25ms
[I 22:24:37.300 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:24:40.577 NotebookApp] Kernel started: 31eb9353-e906-4f06-bab6-81d99d03a06f
[I 22:24:41.410 NotebookApp] Adapting to protocol v5.1 for kernel 31eb9353-e906-4f06-bab6-81d99d03a06f
[W 22:25:08.901 NotebookApp] Forbidden
[W 22:25:08.902 NotebookApp] 403 GET /api/sessions?_=1524950888561 (130.245.70.29) 1.18ms referer=http://35.196.26.71:8888/tree
[W 22:25:08.903 NotebookApp] Forbidden
[W 22:25:08.903 NotebookApp] 403 GET /api/terminals?_=1524950888562 (130.245.70.29) 0.69ms referer=http://35.196.26.71:8888/tree
[I 22:25:20.036 NotebookApp] 302 GET /tree (129.49.100.149) 0.93ms
[I 22:25:22.689 NotebookApp] 302 POST /login?next=%2Ftree (129.49.100.149) 1.33ms
[I 22:25:22.740 NotebookApp] 302 POST /login?next=%2Fnotebooks%2FDataEvents.ipynb (129.49.100.188) 1.02ms
[I 22:25:25.934 NotebookApp] Kernel started: 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[I 22:25:26.454 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[I 22:25:26.846 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[W 22:26:08.905 NotebookApp] Forbidden
[W 22:26:08.905 NotebookApp] 403 GET /api/sessions?_=1524950888563 (130.245.70.29) 1.17ms referer=http://35.196.26.71:8888/tree
[W 22:26:08.906 NotebookApp] Forbidden
[W 22:26:08.906 NotebookApp] 403 GET /api/terminals?_=1524950888564 (130.245.70.29) 0.68ms referer=http://35.196.26.71:8888/tree
[I 22:26:44.642 NotebookApp] 302 GET /notebooks/Category.ipynb (130.245.70.141) 0.96ms
[I 22:26:46.615 NotebookApp] 302 POST /login?next=%2Fnotebooks%2FCategory.ipynb (130.245.70.141) 1.12ms
[I 22:26:47.302 NotebookApp] Kernel started: 35fcb225-41e0-4484-9caf-e54e55567115
[I 22:26:47.822 NotebookApp] Adapting to protocol v5.1 for kernel 35fcb225-41e0-4484-9caf-e54e55567115
[W 22:27:08.902 NotebookApp] Forbidden
[W 22:27:08.903 NotebookApp] 403 GET /api/sessions?_=1524950888565 (130.245.70.29) 1.12ms referer=http://35.196.26.71:8888/tree
[W 22:27:08.904 NotebookApp] Forbidden
[W 22:27:08.904 NotebookApp] 403 GET /api/terminals?_=1524950888566 (130.245.70.29) 0.66ms referer=http://35.196.26.71:8888/tree
[I 22:27:20.189 NotebookApp] 302 GET /tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 1.07ms
[I 22:27:26.732 NotebookApp] Saving file at /DataEvents.ipynb
[W 22:27:33.224 NotebookApp] 401 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 1.74ms referer=http://35.196.26.71:8888/login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[I 22:27:37.892 NotebookApp] Adapting to protocol v5.1 for kernel 31eb9353-e906-4f06-bab6-81d99d03a06f
[W 22:27:42.946 NotebookApp] 401 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 4.81ms referer=http://35.196.26.71:8888/login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D
[I 22:27:54.980 NotebookApp] 302 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 3.01ms
[I 22:27:58.709 NotebookApp] Kernel started: 7e3dc115-a053-4178-b18b-aaeec21fb513
[I 22:27:59.251 NotebookApp] Adapting to protocol v5.1 for kernel 7e3dc115-a053-4178-b18b-aaeec21fb513
[W 22:28:08.902 NotebookApp] Forbidden
[W 22:28:08.902 NotebookApp] 403 GET /api/sessions?_=1524950888567 (130.245.70.29) 1.13ms referer=http://35.196.26.71:8888/tree
[W 22:28:08.903 NotebookApp] Forbidden
[W 22:28:08.903 NotebookApp] 403 GET /api/terminals?_=1524950888568 (130.245.70.29) 0.65ms referer=http://35.196.26.71:8888/tree
[I 22:28:30.539 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[W 22:29:08.907 NotebookApp] Forbidden
[W 22:29:08.907 NotebookApp] 403 GET /api/sessions?_=1524950888569 (130.245.70.29) 1.11ms referer=http://35.196.26.71:8888/tree
[W 22:29:08.908 NotebookApp] Forbidden
[W 22:29:08.908 NotebookApp] 403 GET /api/terminals?_=1524950888570 (130.245.70.29) 0.68ms referer=http://35.196.26.71:8888/tree
[I 22:29:26.798 NotebookApp] Saving file at /DataEvents.ipynb
[W 22:30:08.906 NotebookApp] Forbidden
[W 22:30:08.906 NotebookApp] 403 GET /api/sessions?_=1524950888571 (130.245.70.29) 1.14ms referer=http://35.196.26.71:8888/tree
[W 22:30:08.907 NotebookApp] Forbidden
[W 22:30:08.908 NotebookApp] 403 GET /api/terminals?_=1524950888572 (130.245.70.29) 0.70ms referer=http://35.196.26.71:8888/tree
[W 22:31:08.908 NotebookApp] Forbidden
[W 22:31:08.908 NotebookApp] 403 GET /api/sessions?_=1524950888573 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:31:08.911 NotebookApp] Forbidden
[W 22:31:08.911 NotebookApp] 403 GET /api/terminals?_=1524950888574 (130.245.70.29) 0.77ms referer=http://35.196.26.71:8888/tree
[I 22:31:26.742 NotebookApp] Saving file at /DataEvents.ipynb
[W 22:32:08.903 NotebookApp] Forbidden
[W 22:32:08.904 NotebookApp] 403 GET /api/sessions?_=1524950888575 (130.245.70.29) 1.10ms referer=http://35.196.26.71:8888/tree
[W 22:32:08.905 NotebookApp] Forbidden
[W 22:32:08.905 NotebookApp] 403 GET /api/terminals?_=1524950888576 (130.245.70.29) 0.72ms referer=http://35.196.26.71:8888/tree
[I 22:32:35.988 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:32:40.631 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:32:47.711 NotebookApp] Saving file at /Category.ipynb
[W 22:33:08.911 NotebookApp] Forbidden
[W 22:33:08.912 NotebookApp] 403 GET /api/sessions?_=1524950888577 (130.245.70.29) 1.11ms referer=http://35.196.26.71:8888/tree
[W 22:33:08.913 NotebookApp] Forbidden
[W 22:33:08.913 NotebookApp] 403 GET /api/terminals?_=1524950888578 (130.245.70.29) 0.71ms referer=http://35.196.26.71:8888/tree
[I 22:33:34.347 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[I 22:33:56.371 NotebookApp] Kernel started: 28352512-82df-4637-956b-6233fe195555
[I 22:33:56.977 NotebookApp] Adapting to protocol v5.1 for kernel 28352512-82df-4637-956b-6233fe195555
[I 22:33:59.829 NotebookApp] Saving file at /Category.ipynb
[W 22:34:13.947 NotebookApp] Forbidden
[W 22:34:13.947 NotebookApp] 403 GET /api/sessions?_=1524950888579 (130.245.70.29) 1.11ms referer=http://35.196.26.71:8888/tree
[W 22:34:13.948 NotebookApp] Forbidden
[W 22:34:13.948 NotebookApp] 403 GET /api/terminals?_=1524950888580 (130.245.70.29) 0.68ms referer=http://35.196.26.71:8888/tree
[I 22:34:16.798 NotebookApp] 302 GET /tree (130.245.70.29) 0.86ms
[I 22:34:19.034 NotebookApp] 302 POST /login?next=%2Ftree (130.245.70.29) 1.31ms
[I 22:34:40.637 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:35:34.327 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:35:56.461 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:36:40.670 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:37:40.983 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[I 22:38:40.682 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:39:34.349 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:40:27.485 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:40:40.666 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:40:49.414 NotebookApp] Saving file at /Category.ipynb
[I 22:40:53.219 NotebookApp] Adapting to protocol v5.1 for kernel 35fcb225-41e0-4484-9caf-e54e55567115
[I 22:41:34.337 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:41:49.304 NotebookApp] Kernel started: 6e87ff62-aa56-4960-a40e-ecbf25430f86
[I 22:41:49.841 NotebookApp] Adapting to protocol v5.1 for kernel 6e87ff62-aa56-4960-a40e-ecbf25430f86
[I 22:41:54.640 NotebookApp] Saving file at /Category.ipynb
[I 22:42:40.674 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:42:49.622 NotebookApp] Saving file at /Category.ipynb
[I 22:43:34.365 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:43:49.449 NotebookApp] Saving file at /Revision Analysis.ipynb
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 120, in _handle_event
    event_f()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 364, in _flush
    parent=self.parent_header, ident=self.topic)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 625, in serialize
    content = self.pack(content)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 120, in _handle_event
    event_f()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 364, in _flush
    parent=self.parent_header, ident=self.topic)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 625, in serialize
    content = self.pack(content)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd64352ec80>)
Traceback (most recent call last):
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 120, in _handle_event
    event_f()
  File "/home/xuanli2/penv/lib/python3.5/site-packages/ipykernel/iostream.py", line 364, in _flush
    parent=self.parent_header, ident=self.topic)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 737, in send
    to_send = self.serialize(msg, ident)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 625, in serialize
    content = self.pack(content)
  File "/home/xuanli2/penv/lib/python3.5/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/home/xuanli2/penv/lib/python3.5/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
[I 22:44:37.129 NotebookApp] Saving file at /Category.ipynb
[I 22:44:40.598 NotebookApp] Saving file at /HongyiDuanmu.ipynb
[I 22:44:47.159 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:44:49.486 NotebookApp] Saving file at /Category.ipynb
[I 22:45:34.389 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:45:55.375 NotebookApp] Adapting to protocol v5.1 for kernel 6e87ff62-aa56-4960-a40e-ecbf25430f86
[I 22:46:47.162 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:46:49.402 NotebookApp] Saving file at /Category.ipynb
[I 22:47:34.379 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:48:26.364 NotebookApp] Saving file at /Category.ipynb
[I 22:48:49.418 NotebookApp] Saving file at /Category.ipynb
[W 22:49:52.658 NotebookApp] Replacing stale connection: 0a10fdf0-341e-4ecf-a558-c558ec77caf5:be2757315b314e1e843ec4e296e23cd1
[I 22:49:52.683 NotebookApp] Adapting to protocol v5.1 for kernel 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[I 22:49:54.829 NotebookApp] Kernel interrupted: 28352512-82df-4637-956b-6233fe195555
[I 22:50:15.607 NotebookApp] Kernel interrupted: 28352512-82df-4637-956b-6233fe195555
[I 22:50:47.150 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:50:49.423 NotebookApp] Saving file at /Category.ipynb
[I 22:51:29.631 NotebookApp] Adapting to protocol v5.1 for kernel 31eb9353-e906-4f06-bab6-81d99d03a06f
[I 22:51:34.435 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:52:10.790 NotebookApp] Kernel interrupted: 28352512-82df-4637-956b-6233fe195555
[I 22:52:29.830 NotebookApp] Kernel interrupted: 28352512-82df-4637-956b-6233fe195555
[I 22:52:47.149 NotebookApp] Saving file at /Untitled1.ipynb
[I 22:52:49.424 NotebookApp] Saving file at /Category.ipynb
[I 22:53:01.082 NotebookApp] Saving file at /Category.ipynb
[I 22:53:34.339 NotebookApp] Saving file at /Category.ipynb
[I 22:53:34.463 NotebookApp] Saving file at /DataEvents.ipynb
[I 22:54:20.541 NotebookApp] New terminal with automatic name: 1
[I 22:54:49.422 NotebookApp] Saving file at /Category.ipynb
[I 22:55:34.573 NotebookApp] Kernel started: 8b7af479-ee05-4e02-812f-0e446f7ae66a
[I 22:55:39.712 NotebookApp] Adapting to protocol v5.1 for kernel 8b7af479-ee05-4e02-812f-0e446f7ae66a
[I 22:55:46.769 NotebookApp] Saving file at /playground.ipynb
[I 23:01:06.127 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 23:01:08.213 NotebookApp] Serving notebooks from local directory: /home/xuanli2/CSE-544-Project
[I 23:01:08.213 NotebookApp] 0 active kernels
[I 23:01:08.213 NotebookApp] The Jupyter Notebook is running at:
[I 23:01:08.213 NotebookApp] http://0.0.0.0:8888/
[I 23:01:08.213 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:01:08.408 NotebookApp] 302 GET /notebooks/Revision%20Analysis.ipynb (130.245.70.29) 1.86ms
[I 23:01:09.989 NotebookApp] 302 POST /login?next=%2Fnotebooks%2FRevision%2520Analysis.ipynb (130.245.70.29) 1.29ms
[I 23:01:11.870 NotebookApp] Kernel started: 9221ed58-3822-487e-8cc4-71eb09c4af75
[I 23:01:12.641 NotebookApp] Adapting to protocol v5.1 for kernel 9221ed58-3822-487e-8cc4-71eb09c4af75
[I 23:01:13.475 NotebookApp] New terminal with specified name: 1
[I 23:01:29.257 NotebookApp] Kernel started: 2144b482-ca2a-4963-ac66-5f1b33d2f7c0
[I 23:01:29.844 NotebookApp] Adapting to protocol v5.1 for kernel 2144b482-ca2a-4963-ac66-5f1b33d2f7c0
[W 23:01:31.683 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:01:31.698 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 17.29ms referer=None
[W 23:01:34.660 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:01:34.661 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 3.24ms referer=None
[W 23:01:36.572 NotebookApp] Forbidden
[W 23:01:36.573 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406850 (130.245.70.141) 1.37ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:01:36.627 NotebookApp] Forbidden
[W 23:01:36.628 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 24.33ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[I 23:01:37.773 NotebookApp] 302 GET /notebooks/DataEvents.ipynb (129.49.100.188) 1.51ms
[W 23:01:39.678 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:01:39.679 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 2.84ms referer=None
[I 23:01:45.673 NotebookApp] 302 GET /tree (129.49.100.149) 0.95ms
[I 23:01:48.542 NotebookApp] 302 POST /login?next=%2Ftree (129.49.100.149) 1.19ms
[W 23:01:48.692 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:01:48.693 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 2.81ms referer=None
[W 23:02:05.688 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:02:05.690 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 2.83ms referer=None
[I 23:02:36.086 NotebookApp] Saving file at /playground.ipynb
[I 23:02:37.700 NotebookApp] Saving file at /playground.ipynb
[W 23:02:38.686 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:02:38.687 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 2.76ms referer=None
[W 23:02:49.670 NotebookApp] Forbidden
[W 23:02:49.671 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406852 (130.245.70.141) 1.25ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:02:49.703 NotebookApp] Forbidden
[W 23:02:49.704 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.36ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[I 23:03:12.106 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:03:29.307 NotebookApp] Saving file at /playground.ipynb
[I 23:03:32.287 NotebookApp] Saving file at /playground.ipynb
[W 23:03:43.703 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:03:43.704 NotebookApp] 403 GET /api/kernels/35fcb225-41e0-4484-9caf-e54e55567115/channels?session_id=9e0a9658fbe541c28e06e816774547d2 (130.245.70.141) 2.93ms referer=None
[W 23:04:28.418 NotebookApp] Forbidden
[W 23:04:28.418 NotebookApp] 403 GET /api/config/common?_=1524955160296 (148.75.183.246) 1.20ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[W 23:04:28.423 NotebookApp] Forbidden
[W 23:04:28.423 NotebookApp] 403 GET /api/contents/Untitled1.ipynb?type=notebook&_=1524955160297 (148.75.183.246) 1.13ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[W 23:04:28.426 NotebookApp] Forbidden
[W 23:04:28.426 NotebookApp] 403 GET /api/config/notebook?_=1524955160295 (148.75.183.246) 0.85ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[I 23:04:28.427 NotebookApp] 302 GET /tree?nsukey=ywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 0.72ms
[W 23:04:28.428 NotebookApp] Forbidden
[W 23:04:28.429 NotebookApp] 403 GET /api/contents/Untitled1.ipynb/checkpoints?_=1524955160298 (148.75.183.246) 0.85ms referer=http://35.196.26.71:8888/notebooks/Untitled1.ipynb
[I 23:04:43.394 NotebookApp] 302 POST /login?next=%2Ftree%3Fnsukey%3DywaXax1rDQO2BlwpoyUrH0i5BFb0EspmakE6wQu0D2Fm02BKBCpMF6GYihfNhIZtjOh9t34ZhD5wvq1p6OH739jPOzsBJ1t5XBS6tfMQp9lxVQuHCD7hwZ0GUPPUz2FMeZmm2F12FCSenzQNM0h8kOSbadCLTYE6Dz8RgMMrgqyMSedXb5cWC76BFRhpTy39RV52cYx8707xRUqVLTKfergilqlA3D3D (148.75.183.246) 1.18ms
[W 23:04:49.671 NotebookApp] Forbidden
[W 23:04:49.672 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406853 (130.245.70.141) 1.21ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:04:49.705 NotebookApp] Forbidden
[W 23:04:49.705 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.27ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[I 23:04:49.844 NotebookApp] Kernel started: b70c00f5-3569-4cbb-9990-278e3d6441ab
[I 23:04:50.413 NotebookApp] Adapting to protocol v5.1 for kernel b70c00f5-3569-4cbb-9990-278e3d6441ab
[I 23:05:29.315 NotebookApp] Saving file at /playground.ipynb
[W 23:05:42.524 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:05:42.525 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 3.17ms referer=None
[W 23:05:45.526 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:05:45.528 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 2.89ms referer=None
[W 23:05:49.585 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:05:49.586 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 3.21ms referer=None
[W 23:05:57.645 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:05:57.647 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 2.89ms referer=None
[W 23:05:57.648 NotebookApp] Forbidden
[W 23:05:57.648 NotebookApp] 403 GET /api/sessions?_=1524948252882 (130.245.70.141) 0.74ms referer=http://35.196.26.71:8888/tree?
[W 23:05:57.674 NotebookApp] Forbidden
[W 23:05:57.675 NotebookApp] 403 GET /api/terminals?_=1524948252883 (130.245.70.141) 1.14ms referer=http://35.196.26.71:8888/tree?
[W 23:06:04.506 NotebookApp] Forbidden
[W 23:06:04.506 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406854 (130.245.70.141) 1.23ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:04.537 NotebookApp] Forbidden
[W 23:06:04.537 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.39ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.269 NotebookApp] Forbidden
[W 23:06:05.270 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406855 (130.245.70.141) 1.20ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.302 NotebookApp] Forbidden
[W 23:06:05.302 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.31ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.505 NotebookApp] Forbidden
[W 23:06:05.506 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406856 (130.245.70.141) 1.26ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.537 NotebookApp] Forbidden
[W 23:06:05.538 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.30ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.764 NotebookApp] Forbidden
[W 23:06:05.764 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406857 (130.245.70.141) 1.20ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.795 NotebookApp] Forbidden
[W 23:06:05.796 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.29ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:05.989 NotebookApp] Forbidden
[W 23:06:05.990 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406858 (130.245.70.141) 1.25ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.021 NotebookApp] Forbidden
[W 23:06:06.021 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.33ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.169 NotebookApp] Forbidden
[W 23:06:06.170 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406859 (130.245.70.141) 1.20ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.201 NotebookApp] Forbidden
[W 23:06:06.202 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.30ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.349 NotebookApp] Forbidden
[W 23:06:06.350 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406860 (130.245.70.141) 1.20ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.379 NotebookApp] Forbidden
[W 23:06:06.379 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.28ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.518 NotebookApp] Forbidden
[W 23:06:06.518 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406861 (130.245.70.141) 1.24ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.550 NotebookApp] Forbidden
[W 23:06:06.550 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.29ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.698 NotebookApp] Forbidden
[W 23:06:06.698 NotebookApp] 403 GET /api/contents/Category.ipynb?content=0&_=1524954406862 (130.245.70.141) 1.20ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[W 23:06:06.732 NotebookApp] Forbidden
[W 23:06:06.732 NotebookApp] 403 PUT /api/contents/Category.ipynb (130.245.70.141) 1.44ms referer=http://35.196.26.71:8888/notebooks/Category.ipynb
[I 23:06:09.499 NotebookApp] 302 GET /notebooks/Category.ipynb (130.245.70.141) 0.91ms
[I 23:06:11.528 NotebookApp] 302 POST /login?next=%2Fnotebooks%2FCategory.ipynb (130.245.70.141) 1.26ms
[I 23:06:12.274 NotebookApp] Kernel started: 51b9b359-f98b-41b6-9e1d-7ad69a26f2fb
[I 23:06:12.805 NotebookApp] Adapting to protocol v5.1 for kernel 51b9b359-f98b-41b6-9e1d-7ad69a26f2fb
[W 23:06:13.705 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:06:13.707 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 3.29ms referer=None
[W 23:06:45.770 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:06:45.771 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 2.97ms referer=None
[I 23:06:50.005 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:06:57.099 NotebookApp] 302 POST /login?next=%2Fnotebooks%2FDataEvents.ipynb (129.49.100.188) 1.19ms
[I 23:07:00.414 NotebookApp] Kernel started: 8a43400c-9f2f-4e36-877b-f9deda9308fc
[I 23:07:00.946 NotebookApp] Adapting to protocol v5.1 for kernel 8a43400c-9f2f-4e36-877b-f9deda9308fc
[I 23:07:22.734 NotebookApp] Saving file at /playground.ipynb
[I 23:07:23.001 NotebookApp] Saving file at /playground.ipynb
[I 23:07:26.348 NotebookApp] Saving file at /Category.ipynb
[I 23:07:26.758 NotebookApp] Saving file at /playground.ipynb
[I 23:07:34.442 NotebookApp] Saving file at /DataEvents.ipynb
[W 23:07:49.829 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:07:49.831 NotebookApp] 403 GET /api/kernels/31eb9353-e906-4f06-bab6-81d99d03a06f/channels?session_id=8d4b425ccac64435aac35ea4b2b299a6 (130.245.192.0) 3.27ms referer=None
[W 23:07:51.410 NotebookApp] 404 GET /api/kernels/0a10fdf0-341e-4ecf-a558-c558ec77caf5/channels?session_id=be2757315b314e1e843ec4e296e23cd1 (129.49.100.149): Kernel does not exist: 0a10fdf0-341e-4ecf-a558-c558ec77caf5
[W 23:07:51.424 NotebookApp] 404 GET /api/kernels/0a10fdf0-341e-4ecf-a558-c558ec77caf5/channels?session_id=be2757315b314e1e843ec4e296e23cd1 (129.49.100.149) 16.04ms referer=None
[W 23:07:53.508 NotebookApp] Replacing stale connection: 0a10fdf0-341e-4ecf-a558-c558ec77caf5:be2757315b314e1e843ec4e296e23cd1
[I 23:08:12.311 NotebookApp] Saving file at /Category.ipynb
[I 23:08:50.010 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:09:29.319 NotebookApp] Saving file at /playground.ipynb
[I 23:09:34.452 NotebookApp] Saving file at /DataEvents.ipynb
[I 23:09:36.525 NotebookApp] Saving file at /playground.ipynb
[I 23:09:57.098 NotebookApp] Adapting to protocol v5.1 for kernel 8a43400c-9f2f-4e36-877b-f9deda9308fc
[I 23:10:12.729 NotebookApp] Saving file at /Category.ipynb
[I 23:10:26.076 NotebookApp] Saving file at /playground.ipynb
[I 23:10:28.339 NotebookApp] Saving file at /playground.ipynb
[I 23:10:42.402 NotebookApp] Saving file at /playground.ipynb
[I 23:10:50.025 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:11:30.047 NotebookApp] Saving file at /playground.ipynb
[I 23:11:57.033 NotebookApp] Saving file at /DataEvents.ipynb
[I 23:12:50.019 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:13:57.009 NotebookApp] Saving file at /DataEvents.ipynb
[I 23:14:18.254 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:20.901 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:34.664 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:35.001 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:35.284 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:45.098 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:50.031 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:14:50.601 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:52.698 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:55.644 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:14:56.756 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:00.050 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:03.831 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:04.649 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:04.938 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:06.502 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:08.110 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:13.212 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:15.643 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:27.345 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:30.200 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:33.758 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:42.385 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:49.051 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:54.626 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:58.656 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:15:59.709 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:03.720 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:12.718 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:14.343 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:17.709 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:24.872 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:29.751 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:16:50.026 NotebookApp] Saving file at /Untitled1.ipynb
[I 23:17:11.878 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:26.324 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:27.243 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:30.337 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:33.619 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:35.051 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:39.048 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:40.298 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:41.731 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:50.820 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:54.551 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:17:58.144 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:00.203 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:10.978 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:14.136 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:27.458 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:28.743 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:31.217 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:39.959 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:47.509 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:18:50.031 NotebookApp] Saving file at /Untitled1.ipynb
[W 23:18:57.099 NotebookApp] WebSocket ping timeout after 119943 ms.
[I 23:19:04.392 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:06.759 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:14.466 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:39.128 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:39.942 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:47.870 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:52.677 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:19:58.271 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:02.921 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:03.759 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:04.511 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:09.957 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:10.776 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:13.066 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:14.273 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:21.334 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:29.092 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:30.219 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:40.720 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:43.743 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:20:50.002 NotebookApp] Saving file at /DataTime.ipynb
[I 23:20:53.665 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:21:11.927 NotebookApp] Saving file at /Revision Analysis.ipynb
[I 23:22:50.048 NotebookApp] Saving file at /DataTime.ipynb
[I 23:22:58.784 NotebookApp] Saving file at /playground.ipynb
[I 23:23:29.357 NotebookApp] Saving file at /playground.ipynb
[I 23:32:56.829 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 23:32:58.882 NotebookApp] Serving notebooks from local directory: /home/xuanli2/CSE-544-Project
[I 23:32:58.882 NotebookApp] 0 active kernels
[I 23:32:58.882 NotebookApp] The Jupyter Notebook is running at:
[I 23:32:58.882 NotebookApp] http://0.0.0.0:8888/
[I 23:32:58.882 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:33:01.751 NotebookApp] 302 GET /notebooks/playground.ipynb (130.245.70.29) 1.33ms
[I 23:33:03.243 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fplayground.ipynb (130.245.70.29) 1.25ms
[I 23:33:06.425 NotebookApp] Kernel started: 81d1ec27-e22a-4dcb-9305-360f229523c7
[I 23:33:07.413 NotebookApp] Adapting to protocol v5.1 for kernel 81d1ec27-e22a-4dcb-9305-360f229523c7
[W 23:33:31.082 NotebookApp] 404 GET /api/kernels/9221ed58-3822-487e-8cc4-71eb09c4af75/channels?session_id=1be4cf3b383d4ed283714b42cbdcbbc8 (130.245.70.29): Kernel does not exist: 9221ed58-3822-487e-8cc4-71eb09c4af75
[W 23:33:31.108 NotebookApp] 404 GET /api/kernels/9221ed58-3822-487e-8cc4-71eb09c4af75/channels?session_id=1be4cf3b383d4ed283714b42cbdcbbc8 (130.245.70.29) 28.17ms referer=None
[W 23:33:44.982 NotebookApp] Couldn't authenticate WebSocket connection
[W 23:33:44.983 NotebookApp] 403 GET /api/kernels/8a43400c-9f2f-4e36-877b-f9deda9308fc/channels?session_id=d23965ad845a4c318793d3ad2b64705a (129.49.100.188) 2.99ms referer=None
